CREATE TABLE stg_daily_trades(
  trader VARCHAR(255)
  ,sequence_no VARCHAR(255)
  ,account VARCHAR(255)
  ,side VARCHAR(255)
  ,symbol VARCHAR(255)
  ,quantity VARCHAR(255)
  ,price VARCHAR(255)
  ,destination VARCHAR(255)
  ,contra VARCHAR(255)
  ,trade_datetime VARCHAR(255)
  ,bo_account VARCHAR(255)
  ,cusip VARCHAR(255)
  ,liq VARCHAR(255)
  ,order_id VARCHAR(255)
  ,exec_broker VARCHAR(255)
  ,ecn_fee VARCHAR(255)
  ,order_datetime VARCHAR(255)
  ,specialist VARCHAR(255)
  ,commission VARCHAR(255)
  ,bb_trade VARCHAR(255)
  ,sec_fee VARCHAR(255)
  ,batch_id VARCHAR(255)
  ,client_order_id VARCHAR(255)
  ,prime VARCHAR(255)
  ,cover_quantity VARCHAR(255)
  ,userr VARCHAR(255)
  ,settle_date VARCHAR(255)
  ,principal VARCHAR(255)
  ,net_amount VARCHAR(255)
  ,allocation_id VARCHAR(255)
  ,allocation_role VARCHAR(255)
  ,is_clearable VARCHAR(255)
  ,nscc_fee VARCHAR(255)
  ,nasdaq_fee VARCHAR(255)
  ,clearing_fee VARCHAR(255)
  ,nyse_etf_fee VARCHAR(255)
  ,amex_etf_fee VARCHAR(255)
  ,listing_exchange VARCHAR(255)
  ,native_liq VARCHAR(255)
  ,order_received_id VARCHAR(255)
  ,bo_group_id VARCHAR(255)
);

CREATE TABLE fact_daily_trades(
  trader VARCHAR(50)
  ,sequence_no VARCHAR(10)
  ,account VARCHAR(50)
  ,side VARCHAR(10)
  ,symbol VARCHAR(25)
  ,quantity INTEGER
  ,price DECIMAL
  ,destination VARCHAR(25)
  ,contra VARCHAR(10)
  ,trade_datetime TIMESTAMP
  ,bo_account VARCHAR(25)
  ,cusip VARCHAR(25)
  ,liq VARCHAR(10)
  ,order_id VARCHAR(25)
  ,exec_broker VARCHAR(10)
  ,ecn_fee INTEGER
  ,order_datetime TIMESTAMP
  ,specialist VARCHAR(255)
  ,commission DECIMAL
  ,bb_trade VARCHAR(255)
  ,sec_fee DECIMAL
  ,batch_id VARCHAR(255)
  ,client_order_id VARCHAR(255)
  ,prime VARCHAR(255)
  ,cover_quantity INTEGER
  ,userr VARCHAR(255)
  ,settle_date DATE
  ,principal INTEGER
  ,net_amount DECIMAL
  ,allocation_id VARCHAR(255)
  ,allocation_role VARCHAR(255)
  ,is_clearable BOOLEAN
  ,nscc_fee DECIMAL
  ,nasdaq_fee DECIMAL
  ,clearing_fee DECIMAL
  ,nyse_etf_fee DECIMAL
  ,amex_etf_fee DECIMAL
  ,listing_exchange VARCHAR(255)
  ,native_liq VARCHAR(10)
  ,order_received_id VARCHAR(25)
  ,bo_group_id VARCHAR(4)
);
